#!/usr/bin/env ruby
require 'pg'
require 'sequel'

if ARGV[0].nil?
  puts "You need to specify the postgres connection string as the first argument"
  exit(0)
end

if ARGV[1].nil?
  puts "you need to specify the foreign server name as the second param"
  exit(0)
end

schema_name = ARGV[2] || "public"

db   = Sequel.connect(ARGV[0])
file = File.open("foreign_schema.sql", "wb")
(db.tables | db.views).each do |table|
  statement = <<-SQL
CREATE FOREIGN TABLE #{schema_name}.#{table.to_s} (
#{ db.schema(table).map { |x| %{  "#{x[0].to_s}" #{x[1][:db_type]}} }.join(",\n") }
)
SERVER #{ARGV[1]}
OPTIONS (schema_name 'public', table_name '#{table}');

SQL
  file.puts(statement)
end

puts "done"
